### ISSUE TITLE
Warning PHP Strict Standards:  gmmktime()

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-events#1]
"[Fri Jan 23 12:11:57 2015] [error] [client xxxxxxx] PHP Strict Standards:  gmmktime(): You should be using the time() function instead in /srv/www/....../plugins/fau-events/helpers/event-events-helper.php on line 73"

**Comment by rvdforst** [comment]
Siehe https://github.com/RRZE-Webteam/fau-events/commit/5f6fad8e956b26fa97ed2927d7efdec958c75271
