### ISSUE TITLE
Abo-Link

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-events#11]
Der Abonnement-Link  abonnement_link="1" wird nur angezeigt, wenn künftige Termine vorhanden sind. Kann man den Link auch anzeigen lassen, wenn keine Termine vorhanden sind?

**Comment by rvdforst** [comment]
Gute Idee. Ist schon auf meiner To-Do-Liste eingetragen :) Kommt mit der nächste Version.
