### ISSUE TITLE
Feeds lassen sich nicht hinzufügen

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-events#7]
In der CMS-Instanz vom RRZE lassen sich keine Feeds (.ics) Abonnements hinzufügen. Wenn ich auf die Schaltfläche "+ Neues Abo hinzufügen" klicke, dann tut sich nichts.

**Comment by cibsell** [comment]
Erledigt!

**Comment by xwolfde** [comment]
Woran lag es denn? Können wir dazu etwas in die Doku schreiben?

**Comment by cibsell** [comment]
Keine Ahnung... Heute ließ sich der Knopf betätigen und alles ohne Probleme einfügen. Hängt vielleicht mit dem gestrigen Theme-Update zusammen?
